### ISSUE TITLE
Error in 2023.9.2

### ISSUE THREAD

**Issue by tjorim** [jampez77/Ryanair#11]
I got three new ones, hope you don't mind.

<details>

  <summary>KeyError: 'customerId'</summary>

  ```
  This error originated from a custom integration.
  
  Logger: custom_components.ryanair.coordinator
  Source: custom_components/ryanair/coordinator.py:219
  Integration: Ryanair (documentation, issues)
  First occurred: 16:39:22 (1 occurrences)
  Last logged: 16:39:22
  
  Unexpected error fetching Ryanair data: 'customerId'
  Traceback (most recent call last):
    File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 293, in _async_refresh
      self.data = await self._async_update_data()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/config/custom_components/ryanair/coordinator.py", line 219, in _async_update_data
      self.customerId = refreshedToken[CUSTOMER_ID]
                        ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  KeyError: 'customerId'
  ```
  
  ```
  This error originated from a custom integration.
  
  Logger: custom_components.ryanair.coordinator
  Source: custom_components/ryanair/coordinator.py:164
  Integration: Ryanair (documentation, issues)
  First occurred: 16:39:22 (1 occurrences)
  Last logged: 16:39:22
  
  Unexpected error fetching Ryanair data: 'customerId'
  Traceback (most recent call last):
    File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 293, in _async_refresh
      self.data = await self._async_update_data()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/config/custom_components/ryanair/coordinator.py", line 164, in _async_update_data
      self.customerId = refreshedToken[CUSTOMER_ID]
                        ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  KeyError: 'customerId'
  ```

</details>

### TypeError: argument of type 'NoneType' is not iterable

```
Logger: homeassistant.components.sensor
Source: custom_components/ryanair/sensor.py:70
Integration: Sensor (documentation, issues)
First occurred: 16:39:22 (1 occurrences)
Last logged: 16:39:22

Error while setting up ryanair platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ryanair/sensor.py", line 70, in async_setup_entry
    if (ACCESS_DENIED not in profileCoordinator.data and CAUSE not in profileCoordinator.data and TYPE not in profileCoordinator.data):
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by jampez77** [comment]
I don't mind in the slightest 😀 In fact I welcome it! Thanks for taking the time to report these issues.

I just need to figure out how to refresh the token properly.

The alternative is saving username and password to re-authenticate, but I don't like that one bit.

**Comment by jampez77** [comment]
Fixed in [2023.9.3](https://github.com/jampez77/Ryanair/releases/tag/2023.9.3)

**Comment by tjorim** [comment]
First two are resolved now, that leaves us with:

### KeyError: 'token'

```
This error originated from a custom integration.

Logger: custom_components.ryanair.coordinator
Source: custom_components/ryanair/coordinator.py:83
Integration: Ryanair (documentation, issues)
First occurred: 18:03:10 (2 occurrences)
Last logged: 18:03:14

Unexpected error fetching Ryanair data: 'token'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 293, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ryanair/coordinator.py", line 229, in _async_update_data
    refreshedData = await refreshToken(self, data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ryanair/coordinator.py", line 83, in refreshToken
    TOKEN: rememberMeResponse[TOKEN],
           ~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'token'
```

### TypeError: argument of type 'NoneType' is not iterable

```
Logger: homeassistant.components.sensor
Source: custom_components/ryanair/sensor.py:79
Integration: Sensor (documentation, issues)
First occurred: 18:03:15 (1 occurrences)
Last logged: 18:03:15

Error while setting up ryanair platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ryanair/sensor.py", line 79, in async_setup_entry
    if (ACCESS_DENIED not in profileCoordinator.data and CAUSE not in profileCoordinator.data and TYPE not in profileCoordinator.data):
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by jampez77** [comment]
I think there is a chance you might need to remove the integration and re add it. That being said I'll still have a look at this over the weekend all going well.

**Comment by tjorim** [comment]
Great, that did the trick indeed!
